//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PursuitAlert.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PursuitAlert.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pursuit Alert.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication taking longer than expected.
        /// </summary>
        internal static string AuthenticationExtended {
            get {
                return ResourceManager.GetString("AuthenticationExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating with the servers is taking longer than expected. We&apos;ll keep trying..
        /// </summary>
        internal static string AuthenticationExtendedDetails {
            get {
                return ResourceManager.GetString("AuthenticationExtendedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the server right now. Try again later..
        /// </summary>
        internal static string CantReachServer {
            get {
                return ResourceManager.GetString("CantReachServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} activating in.
        /// </summary>
        internal static string CountdownTimerMessage {
            get {
                return ResourceManager.GetString("CountdownTimerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitCommand {
            get {
                return ResourceManager.GetString("ExitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update vehicle info....
        /// </summary>
        internal static string UpdateVehicleInfoCommand {
            get {
                return ResourceManager.GetString("UpdateVehicleInfoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently active with another device. Please check that your unit ID has been entered correctly..
        /// </summary>
        internal static string VehicleInUse {
            get {
                return ResourceManager.GetString("VehicleInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for internet....
        /// </summary>
        internal static string WaitingInternetConnection {
            get {
                return ResourceManager.GetString("WaitingInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t connect to the servers right now. We&apos;ll keep trying..
        /// </summary>
        internal static string WaitingInternetConnectionDetails {
            get {
                return ResourceManager.GetString("WaitingInternetConnectionDetails", resourceCulture);
            }
        }
    }
}
