//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PursuitAlert.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Secrets : global::System.Configuration.ApplicationSettingsBase {
        
        private static Secrets defaultInstance = ((Secrets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Secrets())));
        
        public static Secrets Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15ngz/7wJH9uHXrn3KZn+6ukfDVOjlEt")]
        public string AWSKeyId {
            get {
                return ((string)(this["AWSKeyId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ceCDlZGoKIWg7p/B1//k6X8LR6ZRxliQyKOqdLjkzi+Xh3isTeEWzwiybBfJSi1f")]
        public string AWSSecretKey {
            get {
                return ((string)(this["AWSSecretKey"]));
            }
        }
    }
}
