//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PursuitAlert.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class States {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal States() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PursuitAlert.Client.Properties.States", typeof(States).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        internal static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating (attempt {0}).
        /// </summary>
        internal static string AuthenticatingAttempt {
            get {
                return ResourceManager.GetString("AuthenticatingAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failure.
        /// </summary>
        internal static string AuthenticationFailure {
            get {
                return ResourceManager.GetString("AuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reach server.
        /// </summary>
        internal static string CantReachServer {
            get {
                return ResourceManager.GetString("CantReachServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected.
        /// </summary>
        internal static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device disconnected.
        /// </summary>
        internal static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device error.
        /// </summary>
        internal static string DeviceError {
            get {
                return ResourceManager.GetString("DeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device found.
        /// </summary>
        internal static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS initializing.
        /// </summary>
        internal static string GPSInitializing {
            get {
                return ResourceManager.GetString("GPSInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signal.
        /// </summary>
        internal static string GPSNoSignal {
            get {
                return ResourceManager.GetString("GPSNoSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for GPS.
        /// </summary>
        internal static string GPSSearching {
            get {
                return ResourceManager.GetString("GPSSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple events.
        /// </summary>
        internal static string MultipleActiveModes {
            get {
                return ResourceManager.GetString("MultipleActiveModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device found.
        /// </summary>
        internal static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not patrolling.
        /// </summary>
        internal static string NotPatrolling {
            get {
                return ResourceManager.GetString("NotPatrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On patrol (moving).
        /// </summary>
        internal static string OnPatrolMoving {
            get {
                return ResourceManager.GetString("OnPatrolMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On patrol (stopped).
        /// </summary>
        internal static string OnPatrolStopped {
            get {
                return ResourceManager.GetString("OnPatrolStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for device.
        /// </summary>
        internal static string SearchingForDevice {
            get {
                return ResourceManager.GetString("SearchingForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server disconnected.
        /// </summary>
        internal static string ServerDisconnected {
            get {
                return ResourceManager.GetString("ServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System ready.
        /// </summary>
        internal static string SystemReady {
            get {
                return ResourceManager.GetString("SystemReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for vehicle information.
        /// </summary>
        internal static string WaitingForVehicle {
            get {
                return ResourceManager.GetString("WaitingForVehicle", resourceCulture);
            }
        }
    }
}
