//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PursuitAlert.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Statistics : global::System.Configuration.ApplicationSettingsBase {
        
        private static Statistics defaultInstance = ((Statistics)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Statistics())));
        
        public static Statistics Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TotalDistanceTraveled {
            get {
                return ((double)(this["TotalDistanceTraveled"]));
            }
            set {
                this["TotalDistanceTraveled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AverageDistancePerPatrol {
            get {
                return ((double)(this["AverageDistancePerPatrol"]));
            }
            set {
                this["AverageDistancePerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AverageSpeedPerPatrol {
            get {
                return ((double)(this["AverageSpeedPerPatrol"]));
            }
            set {
                this["AverageSpeedPerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TopSpeed {
            get {
                return ((double)(this["TopSpeed"]));
            }
            set {
                this["TopSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan TotalStationaryTime {
            get {
                return ((global::System.TimeSpan)(this["TotalStationaryTime"]));
            }
            set {
                this["TotalStationaryTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan TotalMovingTime {
            get {
                return ((global::System.TimeSpan)(this["TotalMovingTime"]));
            }
            set {
                this["TotalMovingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan AverageStationaryTimePerPatrol {
            get {
                return ((global::System.TimeSpan)(this["AverageStationaryTimePerPatrol"]));
            }
            set {
                this["AverageStationaryTimePerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan AverageMovingTimePerPatrol {
            get {
                return ((global::System.TimeSpan)(this["AverageMovingTimePerPatrol"]));
            }
            set {
                this["AverageMovingTimePerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AveragePursuitsPerPatrol {
            get {
                return ((int)(this["AveragePursuitsPerPatrol"]));
            }
            set {
                this["AveragePursuitsPerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long TotalPursuits {
            get {
                return ((long)(this["TotalPursuits"]));
            }
            set {
                this["TotalPursuits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long TotalCode3s {
            get {
                return ((long)(this["TotalCode3s"]));
            }
            set {
                this["TotalCode3s"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long TotalCriticalIncidents {
            get {
                return ((long)(this["TotalCriticalIncidents"]));
            }
            set {
                this["TotalCriticalIncidents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long TotalMoveOvers {
            get {
                return ((long)(this["TotalMoveOvers"]));
            }
            set {
                this["TotalMoveOvers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long TotalPinsDropped {
            get {
                return ((long)(this["TotalPinsDropped"]));
            }
            set {
                this["TotalPinsDropped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AverageCode3sPerPatrol {
            get {
                return ((int)(this["AverageCode3sPerPatrol"]));
            }
            set {
                this["AverageCode3sPerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AverageCriticalIncidentsPerPatrol {
            get {
                return ((int)(this["AverageCriticalIncidentsPerPatrol"]));
            }
            set {
                this["AverageCriticalIncidentsPerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AverageMoveOversPerPatrol {
            get {
                return ((int)(this["AverageMoveOversPerPatrol"]));
            }
            set {
                this["AverageMoveOversPerPatrol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AveragePinsDroppedPerPatrol {
            get {
                return ((int)(this["AveragePinsDroppedPerPatrol"]));
            }
            set {
                this["AveragePinsDroppedPerPatrol"] = value;
            }
        }
    }
}
